### ISSUE TITLE
Won't Work for jackbox 6

### ISSUE THREAD

**Issue by KidNGit** [SomeOrdinarySanya/jackbox-online-patch#2]

**Comment by Kupie** [comment]
Seems like this one got missed in the config files!

It has "require-start-privilege":"true" when every other patch is "false" and "AllowUserSwitching" has a typo

**Comment by SomeOrdinarySanya** [comment]
Will fix, sorr I missed that

**Comment by SomeOrdinarySanya** [comment]
> Seems like this one got missed in the config files!
> 
> It has "require-start-privilege":"true" when every other patch is "false" and "AllowUserSwitching" has a typo

pretty sure the allowuserswitching typo is in the game itself lol

**Comment by SomeOrdinarySanya** [comment]
> > Seems like this one got missed in the config files!
> > It has "require-start-privilege":"true" when every other patch is "false" and "AllowUserSwitching" has a typo
> 
> pretty sure the allowuserswitching typo is in the game itself lol

yep, confirm that.

just updated the patch for pack 6. thanks for reporting it!

**Comment by Kupie** [comment]
The typo is in the game itself?! Hahaha that's awesome

Luckily it doesn't depend on this, require-start-privilege seemed to be the main thing needed

Hugely appreciate the mods by the way! I already bought the games on PC, don't wanna buy them a second time just to play more... portably...
