### ISSUE TITLE
Does not seem to work with 18.1.0+ Firmwire

### ISSUE THREAD

**Issue by Areal1970** [SomeOrdinarySanya/jackbox-online-patch#5]
Attempted to start the game, but it just requires me to link my Nintendo account, no way to bypass it. Thanks!

**Comment by forceofwill2553** [comment]
Doesn't tinfoil's fake link nintendo account work?

**Comment by SomeOrdinarySanya** [comment]
You need to link a Nintendo account. You can use Linkalho
